import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'
 
Vue.use(MLInstaller)
 
export default new MLCreate({
  initial: 'english',
  save: process.env.NODE_ENV === 'production',
  languages: [
    new MLanguage('english').create({
      btn: 'Schedule',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
      soft_drinks:'Soft Drinks',
      term_p1:'The 5 de Genève is a motor boat registered in SWITZERLAND in the Pocket-Yacht category.',
      term_p2:'Recreational leisure activities are offered on Lake Geneva.',
      term_p3:'The Geneva 5 is not intended for the transport of passengers from one point to another. The outings on the lake are circular and for lake recreation. Its guests are brought back to their starting point.',
      term_p4:'The contractual relationship is exercised within the framework of a leisure service and not a transport service, through a service provider who mandates us for this service.',
      term_p5:'The order of this service is made through a dedicated website (www.5degeneve.ch) and the confirmation of the customer\'s email is considered as a contract.',
      term_p6:'The contract may be cancelled at any time in the event of force 4 or higher weather conditions. The boat\'s navigator remains the sole decision-maker for all operations necessary to ensure the safety of all guests.',
      term_p7:'The contract is in full effect (not cancellable) one week before the start of the service.',
      term_p8:'Adress : 10 rue Blavignac',
      term_p9:'1227 Genève',
      term_p10:'Suisse',
      term_p11:'Phone number : + 41 79 944 68 77',
      term_p12:'e-mail :info@5degeneve.ch',
      term_p13:'For judiciaire : Genève'
    }),
 
    new MLanguage('french').create({
      btn: 'Réserver',
      date_less_today: "La date ne peut pas être plus tôt ou égale à aujourd'hui",
      not_correct_date: "Choisissez une autre date!",
      not_correct_time: "Choisissez une autre heure!",
      no_time: "Choisissez l'heure s'il vous plaît!",
      short_time_or_long: "La durée ne peut être inférieure à 3 heures et au maximum à 15 heures",
      logout:'Déconnexion',
      orders_ad_title:'Liste des commandes Administrateur',
      status_all: 'Tous',
      status_check: 'A vérifier',
      status_approved:'Approuvé',
      status_declined: 'Decliné',
      contact_us: 'Contactez-nous',
      s_from: 'à partir de',
      y_disc: 'Votre Discount',
      y_disc_p: 'Votre prix Réduit',
      y_pr: 'Votre prix',
      next_disc: 'Discount sur la commande suivante',
      t_c: 'Termes & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'Liste des commandes',
      f_name: 'Prénom',
      l_name: 'Nom de Famille',
      phone: 'Téléphone',
      email:'Courriel',
      cruise: 'Croisère',
      date: 'Date',
      s_time: 'Heure de départ',
      e_time: 'Heure d\'arrivée',
      num: 'Passagers',
      company: 'Entreprise',
      country: 'Pays',
      city: 'Ville',
      street: 'Rue',
      status: 'Status',
      price: 'Prix',
      d_price: 'Discounted Price',
      paid: 'Payé',
      ta_sign_up_title: 'Login Agence de Voyage',
      pass: 'Mot de passe',
      submit: 'Validation',
      clear: 'Effacement',
      f_pass: 'Mot de passe oublié?',
      reg_act: 'Pas encore enrgistré, S\'il vous plaît cliquez ici!',
      reset_pass_title: 'Agence de voyage réinitialisation du mot de passe',
      e_req: 'Un courriel est requis',
      e_valid: 'Le courriel doit être valable',
      p_req: 'Un mot de passe est requis',
      code: 'Code',
      n_pass: 'Nouveau mot de passe',
      pass_again: 'Ressaisir le mot de passe',
      code_req: 'Un code est requis',
      choose_date: 'Choisissez la date',
      register: 'Enregistrement',
      conf:'Confirmation',
      soft_drinks:'Soft Drinks',
      term_p1:'Le 5 de Genève est un bateau à moteur immatriculé SUISSE de la catégorie Pocket-Yacht.',
      term_p2:'Il est proposé des sorties de loisirs à but récréatifs sur le lac Léman.',
      term_p3:'Le 5 de Genève n’est pas destiné au transport de passager permettant de se rendre d’un point à un autre. Les sorties sur le lac sont circulaires et à but de loisirs lacustres. Ses hôtes sont ramenés à leur point de départ.',
      term_p4:'La relation contractuelle s’exerce dans le cadre d’une prestation de loisir et non pas de transport, par l’intermédiaire d’un prestataire de service qui nous mandate pour cette prestation .',
      term_p5:'La commande de ce service est réalisée par l’entremise d’un site web dédié (www.5degeneve.ch) et la confirmation de l’email du client vaut contrat.',
      term_p6:'Le contrat est annulable en tout temps en cas de météo force 4 ou plus. Le pilote du bateau reste seul décisionnaire de toutes les opérations nécessitées pour assurer la sécurité de ses hôtes.',
      term_p7:'Le contrat est en force (non annulable) une semaine avant le début de la prestation.',
      term_p8:'Adresse : 10 rue Blavignac',
      term_p9:'1227 Genève',
      term_p10:'Suisse',
      term_p11:'Téléphone : + 41 79 944 68 77',
      term_p12:'e-mail :info@5degeneve.ch',
      term_p13:'For judiciaire : Genève'
    }),

    new MLanguage('deutsch').create({
      btn: 'Reservieren',
      date_less_today: "Das Datum darf nicht kleiner oder gleiche heute sein",
      not_correct_date: "Wählen Sie bitte ein anderes Datum!",
      not_correct_time: "Wählen Sie bitte eine andere Zeit!",
      no_time: "Bitte eine Zeit wählen!",
      short_time_or_long: "Bitte wählen sie eine Zeit von minimum 3 Stunden und maxiumum 15 Stunden",
      logout:'Abmelden',
      orders_ad_title:'List of Orders Admin',
      status_all: 'Alle',
      status_check: 'Prüfen',
      status_approved:'Akzeptiert',
      status_declined: 'Abgelehnt',
      contact_us: 'Kontakt',
      s_from: 'ab',
      y_disc: 'Ihr Discount',
      y_disc_p: 'Ihr discountierter Preis',
      y_pr: 'Ihr Preis',
      next_disc: 'Discount bei der nächsten Bestellung',
      t_c: 'Allgemeine Geschäftsbedingungen',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'Liste der Bestellungen',
      f_name: 'Vorname',
      l_name: 'Nachname',
      phone: 'Telefon',
      email:'Email',
      cruise: 'Cruise',
      date: 'Datum',
      s_time: 'Startzeit',
      e_time: 'Stopzeit',
      num: 'Passagiere',
      company: 'Firma',
      country: 'Land',
      city: 'Stadt',
      street: 'Strasse',
      status: 'Status',
      price: 'Preis',
      d_price: 'D Preis',
      paid: 'Paid',
      ta_sign_up_title: 'Alr Reiseagentur registrieren',
      pass: 'Passwort',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Passwort vergessen?',
      reg_act: 'Noch nicht registriert? Bitte hier klicken!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail wird benötigt',
      e_valid: 'E-mail muss korrekt sein',
      p_req: 'Passwort wird benötigt',
      code: 'Code',
      n_pass: 'Neues Passwort',
      pass_again: 'Passwort wiederholen',
      code_req: 'Code is erforderlich',
      choose_date: 'Datum wählen',
      register: 'Registrieren',
      conf:'Bestätigung',
      soft_drinks:'Soft Drinks',
      term_p1:'Die "5 de Genève" ist ein Motorboot in der Pocket-Yacht Kategorie, welche in der Schweiz zugelassen ist.',
      term_p2:'Auf dieser werden Freizeitaktivitäten auf dem Genfer See angeboten.',
      term_p3:'Ein Transport von Passagieren von einem Punkt zu einem anderen ist nicht vorgesehen. Die Ausfahrten auf dem Genfer See bestehen aus einer Rundfahrt und die Gäste werden nach dieser zum Ausgangspunkt zurückgebracht.',
      term_p4:'Die Vertragliche Beziehung existiert im Rahmen einer Freizeitdienstleistung und nicht einer Transportdienstleistung, durch Sie oder einem Dienstleister der uns für unsere Dienste beauftragt.',
      term_p5:'Die Beauftragung der Dienstleistung erfolgt durch unsere dedizierte Webseite (www.5degeneve.ch) und die Bestätigung der Email der Kunden wird als Kontakt angesehen.',
      term_p6:'Der Vertrag kann zu jedem Zeitpunkt annulliert werden, falls Windstärken von 4 oder darüber vorherrschen. Der Bootsführer bleibt zu jedem Zeitpunkt der alleinige Entscheidungsträger für alle notwendigen Operationen um die Sicherheit aller Gäste sicherzustellen.',
      term_p7:'Der Vertrag ist effektiv (nicht mehr kündbar) eine Woche vor Beginn der Dienstleistung,',
      term_p8:'Adresse : 10 rue Blavignac',
      term_p9:'1227 Genève',
      term_p10:'Suisse',
      term_p11:'Telefon : + 41 79 944 68 77',
      term_p12:'e-mail :info@5degeneve.ch',
      term_p13:'Gerichtsstand : CH-Genf'
    }),

    new MLanguage('russian').create({
      btn: 'Расписание',
      date_less_today: "Дата не может быть сегодняшней или более ранней",
      not_correct_date: "Выберите другую дату!",
      not_correct_time: "Выберите другое время!",
      no_time: "Пожалуйста, выберите время",
      short_time_or_long: "Длительность должна быть не менее 3 часов и не более 15",
      logout:'Выход из системы',
      orders_ad_title:'Список заказов',
      status_all: 'Все',
      status_check: 'На проверку',
      status_approved:'Подтверждено',
      status_declined: 'Отклонено',
      contact_us: 'Связаться с нами',
      s_from: 'Начиная с',
      y_disc: 'Ваша скидка',
      y_disc_p: 'Сумма вышей скидки',
      y_pr: 'Итоговая Цена',
      next_disc: 'Скидка на следующий заказ',
      t_c: 'Условия использования',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'Список заказов',
      f_name: 'Имя',
      l_name: 'Фамилия',
      phone: 'Номер телефона',
      email:'Адрес эл. почты',
      cruise: 'Круиз',
      date: 'Дата',
      s_time: 'Время начала',
      e_time: 'Время окончания',
      num: 'Пассажиры',
      company: 'Компания',
      country: 'Страна',
      city: 'Город',
      street: 'Улица',
      status: 'Статус',
      price: 'Цена',
      d_price: 'D Price',
      paid: 'Оплаченный',
      ta_sign_up_title: 'Регистрация для тур агенства',
      pass: 'Пароль',
      submit: 'Подтверждено',
      clear: 'Свободный',
      f_pass: 'Забыли пароль?',
      reg_act: 'Незарегистрированный пользователь. Нажмите здесь для регистрации',
      reset_pass_title: 'Сброс пароля для тур агенства',
      e_req: 'Требуется эл. почта',
      e_valid: 'Должна быть существующая Эл. почта',
      p_req: 'Требуется пароль',
      code: 'Код',
      n_pass: 'Новый пароль',
      pass_again: 'Повторите пароль',
      code_req: 'Требуется код',
      choose_date: 'Выберите дату',
      register: 'Регистрация',
      conf:'Подтверждение',
      soft_drinks:'Безалкогольные напитки',
      term_p1:'"5 de Genève" - моторная лодка, зарегистрированная в ШВЕЙЦАРИИ в категории "Pocket-Yacht".',
      term_p2:'Рекреационные мероприятия предлагаются на Женевском озере.',
      term_p3:'"Geneva 5" не предназначена для перевозки пассажиров из одного пункта в другой. Прогулки по озеру круговые и для озерного отдыха. Его гости возвращаются в исходную точку.',
      term_p4:'Договорные отношения осуществляются в рамках службы досуга, а не транспортной службы, через поставщика услуг, который поручает нам эту услугу.',
      term_p5:'Заказ этой услуги осуществляется через специальный веб-сайт (www.5degeneve.ch), и подтверждение электронной почты клиента считается договором.',
      term_p6:'Контракт может быть расторгнут в любое время в случае форс-мажорных(погодных) обстоятельств 4 или выше. Штурман судна остается единственным лицом, принимающим решения по всем операциям, необходимым для обеспечения безопасности всех гостей.',
      term_p7:'Договор действует в полном объеме (не подлежит расторжению) за неделю до начала обслуживания.',
      term_p8:'Адрес : 10 rue Blavignac',
      term_p9:'1227 Genève',
      term_p10:'Швейцария',
      term_p11:'Телефон : + 41 79 944 68 77',
      term_p12:'e-mail :info@5degeneve.ch',
      term_p13:'For judiciaire : Genève'
    }),

    new MLanguage('chinese').create({
      btn: '学到更多',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
      soft_drinks:'Soft Drinks',
      term_p1:'The 5 de Genève is a motor boat registered in SWITZERLAND in the Pocket-Yacht category.',
      term_p2:'Recreational leisure activities are offered on Lake Geneva.',
      term_p3:'The Geneva 5 is not intended for the transport of passengers from one point to another. The outings on the lake are circular and for lake recreation. Its guests are brought back to their starting point.',
      term_p4:'The contractual relationship is exercised within the framework of a leisure service and not a transport service, through a service provider who mandates us for this service.',
      term_p5:'The order of this service is made through a dedicated website (www.5degeneve.ch) and the confirmation of the customer\'s email is considered as a contract.',
      term_p6:'The contract may be cancelled at any time in the event of force 4 or higher weather conditions. The boat\'s navigator remains the sole decision-maker for all operations necessary to ensure the safety of all guests.',
      term_p7:'The contract is in full effect (not cancellable) one week before the start of the service.',
      term_p8:'Adress : 10 rue Blavignac',
      term_p9:'1227 Genève',
      term_p10:'Suisse',
      term_p11:'Phone number : + 41 79 944 68 77',
      term_p12:'e-mail :info@5degeneve.ch',
      term_p13:'For judiciaire : Genève'
    }),

    new MLanguage('arabic').create({
      btn: 'أعرف أكثر',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
      soft_drinks:'Soft Drinks',
      term_p1:'ال5deGenève هي زورق موتور مسجل في سويسرا في الصنف Pocket-Yacht ',
      term_p2:'تتوفر أنشطه  ترفيهيه علي بحيرة جنيف.',
      term_p3:'ليس المقصود من ال5deGenève  نقال الركاب من نقطه واحده إلى أخرى. نزات على البحيرة هي دائريه وللاستجمام البحيرة. ويتم أعادة ضيوفها إلى نقطه الانطلاق.',
      term_p4:'وتمارس العلاقة التعاقدية في اطار خدمه الترفيه وليس خدمه النقل ، من خلال مقدم الخدمة (وكاله السفر أو الفندق) الذي يكلفنا لهذه الخدمة الاضافيه.',
      term_p5:'يتم ترتيب هذه الخدمة من خلال موقع مخصص (www.5degeneve.ch) ويعتبر تاكيد البريد الكتروني الخاص للعميل مثل اتفاق العقد.',
      term_p6:'يمكن إلغاء العقد في اي وقت في حاله الطقس قوة 4 أو الظروف الجوية الأعلى. و ملاح القارب يبقى صانع القرار الوحيد لجميع العمليات اللازمة لضمان سلامة جميع الضيوف.',
      term_p7:'العقد رسمي (وليس قابل للإلغاء) أسبوع واحد قبل بداية الخدمة.',
      term_p8:'Adress : 10 rue Blavignac',
      term_p9:'1227 Genève',
      term_p10:'Suisse',
      term_p11:'Phone number : + 41 79 944 68 77',
      term_p12:'e-mail :info@5degeneve.ch',
      term_p13:'For judiciaire : Genève'
    })
  ]
})
