import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'
 
Vue.use(MLInstaller)
 
export default new MLCreate({
  initial: 'english',
  save: process.env.NODE_ENV === 'production',
  languages: [
    new MLanguage('english').create({
      btn: 'Learn more',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
    }),
 
    new MLanguage('french').create({
      btn: 'En savoir plus',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
    }),

    new MLanguage('deutsch').create({
      btn: 'Mehr erfahren',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
    }),

    new MLanguage('russian').create({
      btn: 'Читать больше',
     date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
    }),

    new MLanguage('chinese').create({
      btn: '学到更多',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
    }),

    new MLanguage('arabic').create({
      btn: 'أعرف أكثر',
      date_less_today: "The date can not be less than or equal to today's",
      not_correct_date: "Choose another date!",
      not_correct_time: "Choose another time!",
      no_time: "Choose time please!",
      short_time_or_long: "The date duration should be minimum 3 hours and maximum 15 hours",
      logout:'Logout',
      orders_ad_title:'List of Orders Admin',
      status_all: 'All',
      status_check: 'To be checked',
      status_approved:'Approved',
      status_declined: 'Declined',
      contact_us: 'Contact Us',
      s_from: 'starting from',
      y_disc: 'Your Discount',
      y_disc_p: 'your discounted Price',
      y_pr: 'Your Price',
      next_disc: 'Discount on next order',
      t_c: 'Terms & Conditions',
      c_g: 'CONDITIONS GENERALES',
      list_ta_o_t: 'List of Orders',
      f_name: 'First Name',
      l_name: 'Last Name',
      phone: 'Phone',
      email:'Email',
      cruise: 'Cruise',
      date: 'Date',
      s_time: 'Start Time',
      e_time: 'End Time',
      num: 'Passengers',
      company: 'Company',
      country: 'Country',
      city: 'City',
      street: 'Street',
      status: 'Status',
      price: 'Price',
      d_price: 'D Price',
      paid: 'Paid',
      ta_sign_up_title: 'Travel Agency sign up',
      pass: 'Password',
      submit: 'Submit',
      clear: 'Clear',
      f_pass: 'Forget password?',
      reg_act: 'Not registered yet, please click here!',
      reset_pass_title: 'Travel Agency Reset Password',
      e_req: 'E-mail is required',
      e_valid: 'E-mail must be valid',
      p_req: 'Password is required',
      code: 'Code',
      n_pass: 'New password',
      pass_again: 'Password again',
      code_req: 'Code is required',
      choose_date: 'Choose date',
      register: 'Register',
      conf:'Confirmation',
    })
  ]
})
